package web

import (
	"net/http"

	_ "github.com/susamn/obsidian-web/docs" // docs is generated by Swag CLI, you have to import it.
	httpSwagger "github.com/swaggo/http-swagger"
)

// handleSwagger serves the Swagger UI.
func (s *Server) handleSwagger(w http.ResponseWriter, r *http.Request) {
	httpSwagger.WrapHandler(w, r)
}
